### ISSUE TITLE
Draggable Polygons

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/tournament-app#21]
it might be nice to let the user drag fields slightly after drawing them

**Comment by theoandtheb** [comment]
Nicer than clicking and dragging a single point to a new location?  I'd hazard a guess that most users are more likely to miss on one or two points than to get the dimensions perfect but miss the mark on all four exactly the same way.  Canvas should be able to support this, but of all the examples I have seen of drawing polys on a map none of them have offered the capacity to correct a single point.  I wouldn't mind helping those working on the field drawing project to get this sorted, as I would like to know how to solve this, but I'll need some time to get caught up on what has been done to this point.

Just a thought.

**Comment by kevinhughes27** [comment]
an excellent thought - editing single points would be great and might actually solve a couple of the issues I entered here

**Comment by mmasse** [comment]
I found google "my maps" (different than google map maker)  You can create
your own layer on top of google maps.

https://www.google.com/maps/d/
Which can be exported as KML files ?

It has a very user friendly polygon drawing, with Name and Description and
Photo can be added to each Polygon.
Markers and lines are also possible.

You could create a layer per tournament, or one big tournament-app layer
for everyone.....

App referencing
http://stackoverflow.com/questions/1470678/google-maps-my-maps-with-google-maps-api-javascript

**Comment by kevinhughes27** [comment]
I had just opened and was playing with this! this is amazing! Lets investigate further how to best use this

**Comment by mmasse** [comment]
I just noticed that maps get saved directly to my google drive.

ie. I have a new "tournament-app" in the root of my google drive.

**Comment by mmasse** [comment]
More research - Google maps Layers
https://developers.google.com/maps/documentation/javascript/layers

**Comment by kevinhughes27** [comment]
closing in favor of #29
