### ISSUE TITLE
Use field dimension somehow

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/tournament-app#22]
similar to #20
we could correct the field to be the right size after initial drawing (also related to #21)

**Comment by kevinhughes27** [comment]
@mmasse do you know what all zuluru stores for fields? I thought it used images but it uses the google maps api as well and the fields on there are the right dimension and have endzones.

**Comment by kevinhughes27** [comment]
looks like zuluru uses rotated rectangles which are easier to work with but from what I recall super hard for the user to add. 

view-source:http://www.ocua.ca/zuluru/maps/view/field:1

we can re-evaluate if we took the right drawing approach later

**Comment by duims** [comment]
Maybe the best option is to have them draw the whole field and then display the proper end zone. Not sure how to get a good sense of how to scale. 

That or by looking at Zuluru source, we can find how to work with the rotated rectangles as then we can set a size that it auto-snaps to.

**Comment by kevinhughes27** [comment]
I am thinking we keep the drawing of polygons and then do a snap to the closest rotated rectangle afterwards. Or mod the drawing ui to be rectangles from the start, don't know if that is possible

**Comment by kevinhughes27** [comment]
closing in favor of #29
