### ISSUE TITLE
Allow editing of field table

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/tournament-app#24]
the field table itself could be editable (at least the name should be).

Note - at some point I imagine we will add a javascript excel plugin / grid editor (something like http://handsontable.com/) which might be useful here

**Comment by theoandtheb** [comment]
How about replacing the field text display div with an update form showing the name only?  An on-hover and on-touch (or on-focus) handler could slightly alter the colour or transparency of the poly in order to highlight it.

**Comment by kevinhughes27** [comment]
The hover already happens right now. We can do something like this right now by making the name field an input (its super simple I don't know why I didn't do it). 

Note the the fields endpoint works in bulk so its not a typical endpoint
