### ISSUE TITLE
hover on field on map

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/tournament-app#28]
the current hover event only works when hovering on the table it would be cool to do the reverse and also change the color on the map

**Comment by theoandtheb** [comment]
After pounding the table for this feature, I only just noticed it's already in effect.  We may be limited by the fact that users may not bother to notice that they can switch between the default "build" overlay and the "select" overlay with the buttons in the top-right corner.  While in build mode, the existing fields are not likely to be addressable as the canvas is likely prepared to draw an intersecting poly upon clicking.  An on-hover listener might work on desktops, but would cause havoc with mobile devices by initiating a new point for a new, intersecting poly.

They are clearly addressable, so this should be fairly easy to achieve, I'm just not sure if the average user is likely to take the time to toggle over to the "select" overlay, especially if they are expecting to use this page to build more fields.

**Comment by kevinhughes27** [comment]
Yeah I think we can re-style those buttons in the top left and make them more clear. Yeah it is clearly addressable so we should be able to toggle the color and highlight the right row in the table.

I don't think this page would ever be used from mobile as its just for setting up the fields the first time

**Comment by kevinhughes27** [comment]
I suspect we'll find a better solution and not need this in #29. closing
