### ISSUE TITLE
entering fields and locations

### ISSUE THREAD

**Issue by kevinhughes27** [kevinhughes27/tournament-app#4]

**Comment by mmasse** [comment]
For reference for drawing after the points are stored.

Javascript
https://developers.google.com/maps/documentation/javascript/shapes

Android might not be useful
https://developers.google.com/maps/documentation/android/shapes

**Comment by kevinhughes27** [comment]
way ahead of you! https://github.com/kevinhughes27/tournament-app/blob/field-creator/app/assets/javascripts/field_creator.coffee

**Comment by mmasse** [comment]
Sigh, I guess it would help if I looked at what was completed already, lol
:-)

**Comment by kevinhughes27** [comment]
entering fields is done for now I think. I am going to close this and add a new issue for locations specifically
